#%RAML 1.0
title: Ezproxy
version: v1
baseUri: https://github.com/jhu-sheridan-libraries/mod-oriole

documentation:
  - title: ezproxy API
    content: This module provide a backend Ezproxy integration

types:
  resource: !include schemas/resource.json
  stanzas: !include schemas/stanzas.json
  resourceCollection: !include schemas/resources.json
  tagCollection:
    type: object
    properties:
      tags:
        type: string[]
  customFile:
    type: file
    fileTypes: ['*/*'] # any file type allowed
    maxLength: 1048576
  subject: !include schemas/subject.json
  subjectCollection: !include schemas/subjects.json
  errors: !include raml-util/schemas/errors.schema

traits:
  orderable: !include raml-util/traits/orderable.raml
  validate: !include raml-util/traits/validation.raml
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml
  facets: !include raml-util/traits/facets.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml
  get-only: !include raml-util/rtypes/get-only.raml

/ezproxy:
 displayName: Ezproxy
 description: Get Ezproxy database stanzas
 get:
   responses:
     200:
       body:
         text/plain:







