#%RAML 1.0
title: Material Types API
version: v2.2
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Location API
    content: This documents the API calls that can be made to query and manage locations of the system

types:
  location: !include schemas/location.json
  locationCollection: !include schemas/locations.json
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/oriole-locations:
  type:
    collection:
      exampleCollection: !include examples/locations.json
      exampleItem: !include examples/location.json
      schemaCollection: locationCollection
      schemaItem: location
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "name=aaa"},
      pageable
    ]
    description: Return a list of locations
    responses:
      400:
        description: "Bad request"
        body:
          text/plain:
      401:
        description: "Not authorized to perform requested action"
        body:
          text/plain:
  post:
    description: Create a new location
    is: [validate]
  delete:
    description: "Delete all locations"
    is: [language]
    responses:
      204:
        description: "All locations deleted"
      500:
        description: "Internal server error, e.g. due to misconfiguration"
        body:
          text/plain:
            example: "Internal server error, contact administrator"
  /{locationId}:
    description: Pass in the location code
    type:
      collection-item:
        exampleItem: !include examples/location.json
        schema: location
    get:
      is: [ validate ]
      responses:
        400:
          description: "Bad request"
          body:
            text/plain:
        401:
          description: "Not authorized to perform requested action"
          body:
            text/plain:
    put:
      is: [ validate ]
      responses:
        400:
          description: "Bad request"
          body:
            text/plain:
        401:
          description: "Not authorized to perform requested action"
          body:
            text/plain:
    delete:
      is: [ validate ]
      responses:
        400:
          description: "Bad request"
          body:
            text/plain:
        401:
          description: "Not authorized to perform requested action"
          body:
            text/plain:
