#%RAML 1.0
title: Oriole
version: v1
baseUri: https://github.com/jhu-sheridan-libraries/mod-oriole

documentation:
  - title: mod-oriole API
    content: This module provide a backend for the Oriole database tool

types:
  resource: !include schemas/resource.json
  resourceCollection: !include schemas/resource-collection.json
  errors: !include raml-util/schemas/errors.schema

traits:
  orderable: !include raml-util/traits/orderable.raml
  validate: !include raml-util/traits/validation.raml
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml
  facets: !include raml-util/traits/facets.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml
  get-only: !include raml-util/rtypes/get-only.raml

/resources:
  displayName: Resources
  description: Resources Collection
  type:
    collection:
      schemaCollection: resourceCollection
      schemaItem: resource
      exampleCollection: !include examples/resource-collection.sample
      exampleItem: !include examples/resource.sample
  post:
    is: [ validate ]
  get:
    is: [
      searchable: { description: "with valid serchable fields: for example keyword=physics", example: "keyword=chemistry" },
      pageable,
      validate
    ]
    responses:
  /{resourceId}:
    displayName: Resource
    description: Get, Delete or Update a specific resource
    type:
      collection-item:
        schema: resource
        exampleItem: !include examples/resource.sample
    get:
      is: [ validate ]
      responses:
        400:
          description: "Bad request"
          body:
            text/plain:
        401:
          description: "Not authorized to perform requested action"
          body:
            text/plain:
    put:
      is: [ validate ]
      responses:
        400:
          description: "Bad request"
          body:
            text/plain:
        401:
          description: "Not authorized to perform requested action"
          body:
            text/plain:
    delete:
      is: [ validate ]
      responses:
        400:
          description: "Bad request"
          body:
            text/plain:
        401:
          description: "Not authorized to perform requested action"
          body:
            text/plain:





