#%RAML 1.0
title: Material Types API
version: v2.2
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Subjects API
    content: This documents the API calls that can be made to query and manage subjects of the system

types:
  subject: !include schemas/subject.json
  subjectCollection: !include schemas/subjects.json
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/oriole-subjects:
  type:
    collection:
      exampleCollection: !include examples/subjects.json
      exampleItem: !include examples/subject.json
      schemaCollection: subjectCollection
      schemaItem: subject
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "name=aaa"},
      pageable
    ]
    description: Return a list of subjects
    responses:
      400:
        description: "Bad request"
        body:
          text/plain:
      401:
        description: "Not authorized to perform requested action"
        body:
          text/plain:
  post:
    description: Create a new subject
    is: [validate]
  delete:
    description: "Delete all subjects"
    is: [language]
    responses:
      204:
        description: "All subjects deleted"
      500:
        description: "Internal server error, e.g. due to misconfiguration"
        body:
          text/plain:
            example: "Internal server error, contact administrator"
  /{subjectId}:
    description: Pass in the subject code
    type:
      collection-item:
        exampleItem: !include examples/subject.json
        schema: subject
    get:
      is: [ validate ]
      responses:
        400:
          description: "Bad request"
          body:
            text/plain:
        401:
          description: "Not authorized to perform requested action"
          body:
            text/plain:
    put:
      is: [ validate ]
      responses:
        400:
          description: "Bad request"
          body:
            text/plain:
        401:
          description: "Not authorized to perform requested action"
          body:
            text/plain:
    delete:
      is: [ validate ]
      responses:
        400:
          description: "Bad request"
          body:
            text/plain:
        401:
          description: "Not authorized to perform requested action"
          body:
            text/plain:
